name: Run API Tests and Deploy Allure Report to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '23'

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run API tests
        run: mvn clean test -Dtest=OrderedTestSuite

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Zip Allure Report
        run: |
          mkdir allure-report
          cp -r target/allure-results target/allure-report
          zip -r allure-report.zip allure-report

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy Allure Report to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --dir=./ --file=allure-report.zip --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
