name: Run API Tests and Deploy Allure Report to Netlify

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests on (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      reason:
        description: 'Reason for running the workflow'
        required: false
        default: 'Manual trigger'

jobs:
  run_tests_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run API tests
        env:
          ENV: ${{ inputs.environment || 'dev' }}
        run: mvn clean test -Dtest=OrderedTestSuite -Denv=$ENV -Dmaven.test.failure.ignore=true

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Zip Allure Report
        run: |
          mkdir allure-report
          cp -r target/allure-results target/allure-report
          zip -r allure-report.zip allure-report

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy Allure Report to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # Check if the zip file exists
          ls -l allure-report.zip
          
          # Verify Netlify CLI is installed
          netlify --version
          
          # Try deployment with more verbose output
          netlify deploy --dir=allure-report --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN